[theme]
base = "light"
primaryColor = "#FF4B4B" # El rojo de tu marca (puedes cambiarlo)
backgroundColor = "#FFFFFF" # Fondo blanco puro
secondaryBackgroundColor = "#F0F2F6" # Fondo de la barra lateral y widgets (gris muy claro)
textColor = "#262730" # Color del texto (gris oscuro para lectura)