# .streamlit/secrets.toml
[sqlserver]
DRIVER = "{ODBC Driver 18 for SQL Server}"
SERVER = "server-db-park.database.windows.net"
DATABASE = "db-park"
UID = "rw_user_parking"
PWD = "#K!L2f7@Pz9T$h4Gq1Y%e"